version: "3.8"

services:
  backend:
    build: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/app
  frontend:
    build: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: basednfound_user
      POSTGRES_DB: basednfound_dev
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports: 
      - 8080:80

volumes:
  pgdata:
