import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from "./components/Providers";
import { getServerSession } from 'next-auth';
import Link from 'next/link';
import Logout from "./account/logout/logout"
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
        <body className={inter.className}>
          <Providers>
            <nav>{<Link href="/">Home </Link>}{!!session && <Logout/>}{!session && <Link href="/account/login">Login</Link>}</nav>{children}</Providers>
      </body>
    </html>
  )
}
